[package]
name = "book-parse-shell"
version = "0.3.0"
authors = ["Vitaliy Busko <vitaliy.opensource@gmail.com>"]
edition = "2018"

[dependencies]
bpw = { package = "book-parse-wrapper", path = "../wrapper" }
clap = "3.0.0-beta.2"
tokio = { version="1.0", features=["full"] }
