on: [push, pull_request]

name: CI\.NET

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      LD_LIBRARY_PATH: ./lib/x86_64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    steps:
      - uses: actions/checkout@v2
      - run: dotnet test ./src/dotnet/book-parse-bindings.sln
